/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PortfolioProject = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'projectUrl' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const SocialLinks = IDL.Record({
  'linkedin' : IDL.Text,
  'twitter' : IDL.Text,
  'instagram' : IDL.Text,
  'github' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'socialLinks' : SocialLinks,
  'name' : IDL.Text,
  'resumeUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addPortfolioProject' : IDL.Func([PortfolioProject], [PortfolioProject], []),
  'deletePortfolioProject' : IDL.Func([IDL.Nat], [], []),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listPortfolioProjects' : IDL.Func(
      [],
      [IDL.Vec(PortfolioProject)],
      ['query'],
    ),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePortfolioProject' : IDL.Func([PortfolioProject], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PortfolioProject = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'projectUrl' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const SocialLinks = IDL.Record({
    'linkedin' : IDL.Text,
    'twitter' : IDL.Text,
    'instagram' : IDL.Text,
    'github' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'socialLinks' : SocialLinks,
    'name' : IDL.Text,
    'resumeUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addPortfolioProject' : IDL.Func(
        [PortfolioProject],
        [PortfolioProject],
        [],
      ),
    'deletePortfolioProject' : IDL.Func([IDL.Nat], [], []),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listPortfolioProjects' : IDL.Func(
        [],
        [IDL.Vec(PortfolioProject)],
        ['query'],
      ),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePortfolioProject' : IDL.Func([PortfolioProject], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };