/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface PortfolioProject {
  'id' : bigint,
  'title' : string,
  'displayOrder' : bigint,
  'description' : string,
  'imageUrl' : string,
  'projectUrl' : string,
  'techStack' : Array<string>,
}
export interface Profile {
  'bio' : string,
  'title' : string,
  'socialLinks' : SocialLinks,
  'name' : string,
  'resumeUrl' : string,
}
export interface SocialLinks {
  'linkedin' : string,
  'twitter' : string,
  'instagram' : string,
  'github' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addPortfolioProject' : ActorMethod<[PortfolioProject], PortfolioProject>,
  'deletePortfolioProject' : ActorMethod<[bigint], undefined>,
  'getProfile' : ActorMethod<[], Profile>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listPortfolioProjects' : ActorMethod<[], Array<PortfolioProject>>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'updatePortfolioProject' : ActorMethod<[PortfolioProject], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];